%%%-------------------------------------------------------------------
%%% @author Mikael Bylund <mikael.bylund@gmail.com>
%%% @copyright (C) 2016, Mikael Bylund
%%% @doc
%%%
%%% @end
%%% Created : 08. Jun 2016 11:56
%%%-------------------------------------------------------------------
-author("Mikael Bylund <mikael.bylund@gmail.com").

-define(englishWX, #{
          "aboutButton"           => "OK",
          "aboutLbl1"             => "A P2P To-Do manager written in Erlang",
          "aboutLbl2"             => "Developed by:",
          "aboutLbl3"             => "Additions by:",
          "aboutLbl4"             => "Art and Icons:",
          "aboutLbl5"             => "See Open Icon Library at",
          "aboutLbl6"             => "Licence:",
          "aboutMenu"             => "About",
          "addListButton"         => #{tooltip  => "Add task to list"},
          "addOwnerButton"        => #{tooltip  => "Manage owners"},
          "addTaskInboxMenu"      => "Add task to inbox\tCtrl+Shift+N",
          "addTaskMenu"           => "Add task at bottom\tCtrl+N",
          "backTool"              => #{label    => "Back",
                                       tooltip  => "Go back",
                                       longhelp => "Go back to parent todo"},
          "backupMenuItem"        => "Backup database",
          "bookmarkBtn"           => #{tooltip  => "Bookmark view"},
          "checkBoxUseFilter"     => #{label   => "Filter",
                                       tooltip => "Use configured filter"},
          "chooseListLang"        => "Choose list:",
          "commentArea"           => #{tooltip  => "Comments"},
          "commentArea1"          => #{tooltip  => "Comments"},
          "commentArea2"          => #{tooltip  => "Comments"},
          "commentButton"         => #{tooltip  => "Add comment"},
          "completeLang"          => "% complete",
          "configureSearch"       => #{tooltip  => "Configure which fields to search in"},
          "conflictDlg"           => #{title => "Solve conflict by updating local todo or using remote todo"},
          "conflictLocalLbl"      => "Local Todo",
          "conflictRemoteLbl"     => "Remote Todo",
          "copyMenu"              => "Copy task\tShift+Ctrl+C",
          "copyTool"              => #{label    => "Copy",
                                       tooltip  => "Copy",
                                       longhelp => "Copy task"},
          "createBookmarkButton"  => "Add",
          "createListButton"      => "Add",
          "createOwnerButton"     => "Add",
          "cRemoteDueDateLbl"     => "Due date",
          "cRemoteOwnerLbl"       => "Owner",
          "cRemotePrioLbl"        => "Priority",
          "cRemoteProgress"       => "% complete",
          "cRemoteSharedLbl"      => "Shared",
          "cRemoteStatusLbl"      => "Status",
          "cLocalDueDateLbl"      => "Due date",
          "cLocalOwnerLbl"        => "Owner",
          "cLocalPrioLbl"         => "Priority",
          "cLocalProgress"        => "% complete",
          "cLocalSharedLbl"       => "Shared",
          "cLocalStatusLbl"       => "Status",
          "cutMenu"               => "Cut task\tShift+Ctrl+X",
          "cutTool"               => #{label    => "Cut",
                                       tooltip  => "Cut",
                                       longhelp => "Cut task"},
          "deleteMenu"            => "Delete task\tShift+Ctrl+D",
          "deleteTool"            => #{label    => "Delete",
                                       tooltip  => "Delete",
                                       longhelp => "Delete task"},
          "descriptionArea"       => #{tooltip  => "Description"},
          "descriptionArea1"      => #{tooltip  => "Description"},
          "descriptionArea2"      => #{tooltip  => "Description"},
          "dueDateLang"           => "Due date:",
          "dueDateUsed"           => #{tooltip  => "Use due date"},
          "editMenu"              => "Edit",
          "eTodoHostName"         => #{tooltip  => "The hostname that will be reported to other peers so they can use it to connect to this client."},
          "eTodoPort"             => #{tooltip  => "Starting port to try with, will be incremented if port is busy."},
          "execCmd"               => #{tooltip  => "Run entered command when a reminder occurs(can be used to play a sound)"},
          "executeCmd"            => "Execute cmd:",
          "execTimCmd"            => #{tooltip  => "Run entered command when the timer occurs(can be used to play a sound)",
                                       label    => "Execute cmd:"},
          "exitMenuItem"          => "Exit\tAlt+F4",
          "fileMenu"              => "File",
          "forwardTool"           => #{label    => "Forward",
                                       tooltip  => "Go to sub todo",
                                       longhelp => "Go to sub todo"},
          "helpMenu"              => "Help",
          "helpMenu1"             => "Help\tF1",
          "hostName"              => #{tooltip  => "Host name of the peer you want to connect to"},
          "hourTimer"             => #{tooltip  => "Hours"},
          "linkFileMenu"          => "Link to file\tCtrl+I",
          "linkTimeReportMenu"    => "Link to time report",
          "linkViewMenu"          => "Link to view",
          "listCancel"            => "Cancel",
          "listDlg"               => #{title => "Assign lists to task"},
          "listOk"                => "OK",
          "listsLang"             => "Lists:",
          "loginCancel"           => "Cancel",
          "loginDlg"              => #{title => "Login to ETodo circle"},
          "loginMenuItem"         => "Login\tCtrl+L",
          "loginOk"               => "OK",
          "loginUserName"         => "User name:",
          "loginCircleName"       => "Circle name:",
          "loginCirclePasswd"     => "Circle Password:",
          "logoutMenuItem"        => "Logout",
          "logTimeOnTaskLabel"    => "Log time on task",
          "logWorkButton"         => #{tooltip  => "Log time on task"},
          "logWorkCancel"         => "Cancel",
          "logWorkDlg"            => #{title => "Log work"},
          "logWorkOk"             => "OK",
          "lwDate"                => "Date",
          "lwDesc"                => "Description",
          "lwEstimate"            => "Time estimate",
          "lwTime"                => "Log work",
          "lwTimeSpent"           => "Time spent",
          "lwTimeLeft"            => "Time left",
          "mainPanel"             => "Task view",
          "manageBookmarkCancel"  => "Cancel",
          "manageBookmarkDlg"     => #{title => "Manage bookmarks"},
          "manageBookmarkOk"      => "OK",
          "manageListsButton"     => #{tooltip  => "Manage lists"},
          "manageListCancel"      => "Cancel",
          "manageListDlg"         => #{title => "Manage lists"},
          "manageListOk"          => "OK",
          "manageOwnerCancel"     => "Cancel",
          "manageOwnerDlg"        => #{title => "Manage owners"},
          "manageOwnerOk"         => "OK",
          "messagePanel"          => "Messages",
          "minTimer"              => #{tooltip  => "Minutes"},
          "moveColDownButton"     => "Down",
          "moveColUpButton"       => "Up",
          "moveDownMenu"          => "Move down\tAlt+Down",
          "moveDownTool"          => #{label    => "Move Down",
                                       tooltip  => "Move Down",
                                       longhelp => "Move task down in list"},
          "moveFirstMenu"         => "Move first\tCtrl+Up",
          "moveLastMenu"          => "Move last\tCtrl+Down",
          "moveUpMenu"            => "Move up\tAlt+Up",
          "moveUpTool"            => #{label    => "Move up",
                                       tooltip  => "Move up",
                                       longhelp => "Move task up in list"},
          "ownerLang"             => "Owner:",
          "pasteMenu"             => "Paste task\tShift+Ctrl+V",
          "pasteTool"             => #{label    => "Paste",
                                       tooltip  => "Paste",
                                       longhelp => "Paste task"},
          "peerAvailableIcon"     => #{tooltip  => "Available"},
          "peerAwayIcon"          => #{tooltip  => "Away"},
          "peerBusyIcon"          => #{tooltip  => "Busy"},
          "peerPort"              => #{tooltip  => "Port of the peer you want to connect to"},
          "peerUserName"          => #{tooltip  => "User name of the peer you want to connect to"},
          "pluginCancel"          => "Cancel",
          "pluginDesc"            => "A longer description of the plugin which appears when the plugin is selected in the list to the left.",
          "pluginDescLbl"         => "Description",
          "pluginDlg"             => #{title => "Plugin configuration"},
          "pluginOk"              => "OK",
          "pluginMenuItem"        => "Plugins",
          "printMenuItem"         => "Print\tCtrl+P",
          "priorityChoice"        => #{contents => ["-", "Low", "Medium", "High"]},
          "priorityChoice1"       => #{contents => ["-", "Low", "Medium", "High"]},
          "priorityChoice2"       => #{contents => ["-", "Low", "Medium", "High"]},
          "priorityLang"          => "Priority:",
          "proxyLinkMenu"         => "Make proxy link",
          "recurrence"            => #{contents => ["every 15 min", "every hour", "every 2 hours", "every 4 hours", "every day", "every week", "every 30 days", "every year"]},
          "redoMenu"              => "Redo\tCtrl+Y",
          "redoTool"              => #{label    => "Redo",
                                       tooltip  => "Redo",
                                       longhelp => "Redo changes to tasks"},
          "reminderCancel"        => "Cancel",
          "reminderDlg"           => #{title => "Configure reminder"},
          "reminderPanel"         => "Reminders",
          "reminderOk"            => "OK",
          "removeBookmarkButton"  => "Remove",
          "removeListButton"      => "Remove",
          "removeOwnerButton"     => "Remove",
          "replyAllMenu"          => "Reply all\tShift+Ctrl+R",
          "replyMenu"             => "Reply sender\tCtrl+R",
          "restoreMenuItem"       => "Restore database",
          "schedulePanel"         => "Schedule",
          "searchCancel"          => "Cancel",
          "searchColumns"         => #{contents => ["Comment", "Create time", "Description", "Done time", "Due time", "Id", "Owner", "Priority", "Shared with", "Status"]},
          "searchDlg"             => "Search in columns",
          "searchOk"              => "OK",
          "searchText"            => #{tooltip  => "Enter search. Searches begining with re~ will trigger a regexp search. Searches begining with as~ will trigger an advanced search."},
          "secTimer"              => #{tooltip  => "Seconds"},
          "sendTaskButton"        => #{tooltip  => "Send message about task update"},
          "setAvatarMenuItem"     => "Set avatar",
          "setConInfoLbl"         => "Connection Info",
          "setHostLbl"            => "Host name:",
          "setLocalHostLbl"       => "Local host name:",
          "setLocalPortLbl"       => "Local port:",
          "setPassword"           => "Password:",
          "setPeerInfoLbl"        => "Peer info",
          "setPeerLbl"            => "Peer user name:",
          "setPortLbl"            => "Port:",
          "setThemeLbl"           => "Theme:",
          "setWebPortLbl"         => "Port:",
          "settingsCancel"        => "Cancel",
          "settingsDlg"           => #{title => "Network Settings"},
          "settingsOk"            => "OK",
          "setWebUILbl"           => "Web UI",
          "setRecurrence"         => "Recurrence:",
          "setReminderButton"     => #{tooltip  => "Set reminder for task"},
          "settingsMenu"          => "Network settings",
          "shareButton"           => #{tooltip  => "Share task with user"},
          "sharedLang"            => "Shared:",
          "sharedWithText1"       => #{tooltip  => "A list of users assigned to the task separated by semicolon."},
          "sharedWithText2"       => #{tooltip  => "A list of users assigned to the task separated by semicolon."},
          "statusLang"            => "Status:",
          "showInReportLabel"     => "Show task in report",
          "showLogin"             => "Show login dialog at startup",
          "sortColumnsDlg"        => "Order columns",
          "sortColumnsCancel"     => "Cancel",
          "sortColumnsOk"         => "OK",
          "statusChoice"          => #{contents => ["-", "Planning", "In progress", "Done"]},
          "statusChoice1"         => #{contents => ["-", "Planning", "In progress", "Done"]},
          "statusChoice2"         => #{contents => ["-", "Planning", "In progress", "Done"]},
          "timerDescLbl"          => "Description:",
          "timerCancel"           => "Cancel",
          "timerDlg"              => #{title => "Timer (Pomodoro)"},
          "timerOk"               => "OK",
          "timeEstimate"          => #{tooltip  => "Hours"},
          "timeLogCheckBox"       => "Show done task in \"Time log\"",
          "timeLogPanel"          => "Time log",
          "timeRemaining"         => #{tooltip  => "Hours"},
          "timerTool"             => "Timer",
          "todoDownTool"          => #{label    => "Add at bottom",
                                       tooltip  => "Add at bottom",
                                       longhelp => "Add task at bottom of list"},
          "todoUpTool"            => #{label    => "Add at top",
                                       tooltip  => "Add at top",
                                       longhelp => "Add task at top of list"},
          "undoMenu"              => "Undo\tCtrl+Z",
          "undoTool"              => #{label    => "Undo",
                                       tooltip  => "Undo",
                                       longhelp => "Undo changes to tasks"},
          "updateBookmarkButton"  => "Update",
          "updateListButton"      => "Update",
          "updateOwnerButton"     => "Update",
          "useEndDate"            => "End date:",
          "useLocalButton"        => "Use Local Todo",
          "userCancel"            => "Cancel",
          "userDlg"               => #{title => "Share task with users"},
          "userOk"                => "OK",
          "useReminder"           => "Start date:",
          "useRemoteButton"       => "Use Remote Todo",
          "userStatusChoice"      => #{contents => ["Offline", "Available", "Away", "Busy"]},
          "useStartTime"          => "Start time:",
          "peerStatusMsg"         => "Select a peer to show status information here...",
          "userStatusMsg"         => #{tooltip  => "Enter status message to be shown"},
          "webPort"               => #{tooltip  => "Starting port to try with, will be incremented if port is busy."},
          "webUIEnabled"          => "Activate Web UI",
          "workHours"             => #{tooltip  => "Hours"},
          "workLogCheckBox"       => "Show task with no time in \"Work log\"",
          "workLogLabel"          => "The report shows the logged work for a five day period, choose the start date:",
          "workLogPanel"          => "Work log",
          "workMinutes"           => #{tooltip  => "Minutes"}
         }).

-define(englishDef, #{
          all               => "All",
          assigned          => "Assigned",
          available         => "Available",
          away              => "Away",
          busy              => "Busy",
          clearMsgText      => "Clear \"Messages\" tab",
          clearRemText      => "Clear \"Reminders\" tab",
          comment           => "Comment",
          compact           => "Compact",
          createTime        => "Create time",
          def               => "Default",
          defInbox          => "Inbox",
          defLoggedWork     => "-- Logged work --",
          defSchedule       => "---- Schedule ----",
          defShowStatus     => "-- Show status --",
          defTaskList       => "All tasks",
          defTimeReport     => "-- Time report --",
          description       => "Description",
          done              => "Done",
          doneTime          => "Done time",
          dueTime           => "Due date",
          estimate          => "Estimate(h)",
          high              => "High",
          inProgress        => "In progress",
          listsMenu         => "Lists",
          low               => "Low",
          medium            => "Medium",
          offline           => "Offline",
          orderCol          => "Order columns",
          owner             => "Owner",
          planning          => "Planning",
          priority          => "Priority",
          progress          => "Progress(%)",
          remaining         => "Remaining(h)",
          sbNotLoggedIn     => "Not logged in",
          sharedWith        => "Shared with",
          showCol           => "Show columns",
          sortAsc           => "Sort order ascending",
          sortDec           => "Sort order descending",
          sortDef           => "Sort order default",
          status            => "Status",
          statusMenu        => "Status",
          uid               => "Id",
          undefined         => "-",
          overdue           => "Overdue",
          today             => "Today",
          tomorrow          => "Tomorrow",
          weeksAway         => "Week(s) away",
          monthsAway        => "Month(s) away",
          monday            => "Monday",
          tuesday           => "Tuesday",
          wednesday         => "Wednesday",
          thursday          => "Thursday",
          friday            => "Friday",
          saturday          => "Saturday",
          sunday            => "Sunday",
          nextAlarm         => "Next alarm",
          timeLeft          => "Time left(h)",
          timeSpent         => "Time spent(h)",
          timeEstimate      => "Time estimate(h)",
          taskDesc          => "Task description",
          total             => "Total",
          msgWebClient      => "/eWeb:index shows your todos in a browser.",
          msgAltWebClient   => "/eWeb:mobile for an alternative web gui for the phone."
         }).

%% The key value pairs in englishToDB
%% should be same as englishDef, but value as key and key as value.
-define(englishToDB, #{
          "-"                => undefined,
          "All tasks"        => defTaskList,
          "All"              => all,
          "Available"        => available,
          "Away"             => away,
          "Busy"             => busy,
          "Comment"          => comment,
          "Compact"          => compact,
          "Create time"      => createTime,
          "Default"          => def,
          "Description"      => description,
          "Done time"        => doneTime,
          "Done"             => done,
          "Due date"         => dueTime,
          "every 15 min"     => time15,
          "every 2 hours"    => time2h,
          "every 30 days"    => timeMonth,
          "every 4 hours"    => time4h,
          "every day"        => timeDay,
          "every hour"       => time1h,
          "every week"       => timeWeek,
          "every year"       => timeYear,
          "High"             => high,
          "Id"               => uid,
          "In progress"      => inProgress,
          "Low"              => low,
          "Medium"           => medium,
          "Offline"          => offline,
          "Owner"            => owner,
          "Planning"         => planning,
          "Priority"         => priority,
          "Shared with"      => shared,
          "Status"           => status
         }).