%%%-------------------------------------------------------------------
%%% @author Mikael Bylund <mikael.bylund@gmail.com>
%%% @copyright (C) 2016, Mikael Bylund
%%% @doc
%%%
%%% @end
%%% Created : 08. Jun 2016 11:56
%%%-------------------------------------------------------------------
-author("Mikael Bylund <mikael.bylund@gmail.com").

-define(swedishWX, #{
          "aboutButton"           => "OK",
          "aboutLbl1"             => "En P2P Uppgifthanterare skriven i Erlang",
          "aboutLbl2"             => "Utvecklad av:",
          "aboutLbl3"             => "Tillägg av:",
          "aboutLbl4"             => "Ikoner och grafik:",
          "aboutLbl5"             => "Se Open Icon Library",
          "aboutLbl6"             => "Inkluderad 3:rd part mjukvara",
          "aboutMenu"             => "Om",
          "addListButton"         => #{tooltip  => "Lägg till uppgift till lista"},
          "addOwnerButton"        => #{tooltip  => "Hantera ägare"},
          "addTaskInboxMenu"      => "Lägg till uppgift till inbox\tCtrl+Shift+N",
          "addTaskMenu"           => "Lägg till uppgift på slutet\tCtrl+N",
          "backTool"              => #{label    => "Bakåt",
                                       tooltip  => "Gå bakåt",
                                       longhelp => "Gå bakåt till förälderuppgift"},
          "backupMenuItem"        => "Databasbackup",
          "bookmarkBtn"           => #{tooltip  => "Hantera bokmärken"},
          "checkBoxUseFilter"     => #{label   => "Filter",
                                       tooltip => "Använd konfigurerat filter"},
          "chooseListLang"        => "Välj lista:",
          "commentArea"           => #{tooltip  => "Kommentarer"},
          "commentArea1"          => #{tooltip  => "Kommentarer"},
          "commentArea2"          => #{tooltip  => "Kommentarer"},
          "commentButton"         => #{tooltip  => "Skriv kommentar"},
          "completeLang"          => "% färdig",
          "configureSearch"       => #{tooltip  => "Konfigurera vilka fält som ska användas vid sökning"},
          "conflictDlg"           => #{title => "Lös konflikt genom att uppdatera lokal uppgift eller använda cirkelns uppgift"},
          "conflictLocalLbl"      => "Lokal uppgift",
          "conflictRemoteLbl"     => "Cirkelns uppgift",
          "copyMenu"              => "Kopiera uppgift\tShift+Ctrl+C",
          "copyTool"              => #{label    => "Kopiera",
                                       tooltip  => "Kopiera",
                                       longhelp => "Kopiera uppgift"},
          "createBookmarkButton"  => "Lägg till",
          "createListButton"      => "Lägg till",
          "createOwnerButton"     => "Lägg till",
          "cRemoteDueDateLbl"     => "Deadline",
          "cRemoteOwnerLbl"       => "Ägare",
          "cRemotePrioLbl"        => "Prioritet",
          "cRemoteProgress"       => "% färdig",
          "cRemoteSharedLbl"      => "Delad",
          "cRemoteStatusLbl"      => "Status",
          "cLocalDueDateLbl"      => "Deadline",
          "cLocalOwnerLbl"        => "Ägare",
          "cLocalPrioLbl"         => "Prioritet",
          "cLocalProgress"        => "% färdig",
          "cLocalSharedLbl"       => "Delad",
          "cLocalStatusLbl"       => "Status",
          "cutMenu"               => "Klipp ut uppgift\tShift+Ctrl+X",
          "cutTool"               => #{label    => "Klipp ut",
                                       tooltip  => "Klipp ut",
                                       longhelp => "Klipp ut uppgift"},
          "deleteMenu"            => "Ta bort uppgift\tShift+Ctrl+D",
          "deleteTool"            => #{label    => "Ta bort",
                                       tooltip  => "Ta bort",
                                       longhelp => "Ta bort uppgift"},
          "descriptionArea"       => #{tooltip  => "Beskrivning"},
          "descriptionArea1"      => #{tooltip  => "Beskrivning"},
          "descriptionArea2"      => #{tooltip  => "Beskrivning"},
          "dueDateLang"           => "Deadline:",
          "dueDateUsed"           => #{tooltip  => "Använd deadline"},
          "editMenu"              => "&Redigera",
          "eTodoHostName"         => #{tooltip  => "Datornamn som kommer att skickas till andra peers så de kan använda det vid anslutning till denna klient."},
          "eTodoPort"             => #{tooltip  => "Portnummer att starta med, kommer att ökas om porten är upptagen."},
          "execCmd"               => #{tooltip  => "Kör inskrivet kommando när en påminnelse inträffar(kan tex. användas för att spela upp ett ljud)"},
          "executeCmd"            => "Kör:",
          "execTimCmd"            => #{tooltip  => "Kör inskrivet kommando när en påminnelse inträffar(kan tex. användas för att spela upp ett ljud)",
                                       label    => "Kör kommando:"},
          "exitMenuItem"          => "Avsluta\tAlt+F4",
          "fileMenu"              => "Fil",
          "forwardTool"           => #{label    => "Framåt",
                                       tooltip  => "Gå till deluppgift",
                                       longhelp => "Gå till deluppgift"},
          "helpMenu"              => "Hjälp",
          "helpMenu1"             => "Hjälp\tF1",
          "hostName"              => #{tooltip  => "Datornamn till den peer du vill ansluta till"},
          "hourTimer"             => #{tooltip  => "Timmar"},
          "linkFileMenu"          => "Länka fil\tCtrl+I",
          "linkTimeReportMenu"    => "Länka till tidsrapport",
          "linkViewMenu"          => "Länka vy",
          "listCancel"            => "Avbryt",
          "listDlg"               => #{title => "Tilldela listor till uppgift"},
          "listOk"                => "OK",
          "listsLang"             => "Listor:",
          "loginCancel"           => "Avbryt",
          "loginDlg"              => #{title => "Logga in på cirkel"},
          "loginMenuItem"         => "Logga in\tCtrl+L",
          "loginOk"               => "OK",
          "loginUserName"         => "Användarnamn:",
          "loginCircleName"       => "Cirkelnamn:",
          "loginCirclePasswd"     => "Cirkel-lösenord:",
          "logoutMenuItem"        => "Logga ut",
          "logTimeOnTaskLabel"    => "Skriv tid på uppgift",
          "logWorkButton"         => #{tooltip  => "Skriv tid på uppgift"},
          "logWorkCancel"         => "Avbryt",
          "logWorkDlg"            => #{title => "Skriv tid"},
          "logWorkOk"             => "OK",
          "lwDate"                => "Datum",
          "lwDesc"                => "Beskrivning",
          "lwEstimate"            => "Tidsuppskattning",
          "lwTime"                => "Skriv tid",
          "lwTimeSpent"           => "Tid lagd",
          "lwTimeLeft"            => "Tid kvar",
          "mainPanel"             => "Uppgifter",
          "manageBookmarkCancel"  => "Avbryt",
          "manageBookmarkDlg"     => #{title => "Hantera bokmärken"},
          "manageBookmarkOk"      => "OK",
          "manageListsButton"     => #{tooltip  => "Hantera listor"},
          "manageListCancel"      => "Avbryt",
          "manageListDlg"         => #{title => "Hantera listor"},
          "manageListOk"          => "OK",
          "manageOwnerCancel"     => "Avbryt",
          "manageOwnerDlg"        => #{title => "Hantera ägare"},
          "manageOwnerOk"         => "OK",
          "messagePanel"          => "Meddelanden",
          "minTimer"              => #{tooltip  => "Minuter"},
          "moveColDownButton"     => "Ned",
          "moveColUpButton"       => "Upp",
          "moveDownMenu"          => "Flytta ned\tAlt+Down",
          "moveDownTool"          => #{label    => "Flytta ned",
                                       tooltip  => "Flytta ned",
                                       longhelp => "Flytta ned uppgift i listan"},
          "moveFirstMenu"         => "Flytta först\tCtrl+Up",
          "moveLastMenu"          => "Flytta sist\tCtrl+Down",
          "moveUpMenu"            => "Flytta up\tAlt+Up",
          "moveUpTool"            => #{label    => "Flytta upp",
                                       tooltip  => "Flytta upp",
                                       longhelp => "Flytta upp uppgift i listan"},
          "ownerLang"             => "Ägare:",
          "pasteMenu"             => "Klista in uppgift\tShift+Ctrl+V",
          "pasteTool"             => #{label    => "Klistra in",
                                       tooltip  => "Klistra in",
                                       longhelp => "Klistra in uppgift"},
          "peerAvailableIcon"     => #{tooltip  => "Tillgänglig"},
          "peerAwayIcon"          => #{tooltip  => "Borta"},
          "peerBusyIcon"          => #{tooltip  => "Upptagen"},
          "peerPort"              => #{tooltip  => "Portnummer till den peer du vill ansluta till"},
          "peerUserName"          => #{tooltip  => "Användarnamn till den peer du vill ansluta till"},
          "pluginCancel"          => "Avbryt",
          "pluginDesc"            => "En längre beskrivning av den plugin som visas när den är vald i listan till vänster.",
          "pluginDescLbl"         => "Beskrivning",
          "pluginDlg"             => #{title => "Plugin konfiguration"},
          "pluginOk"              => "OK",
          "pluginMenuItem"        => "Plugins",
          "printMenuItem"         => "Skriv ut\tCtrl+P",
          "priorityChoice"        => #{contents => ["-", "Låg", "Medel", "Hög"]},
          "priorityChoice1"       => #{contents => ["-", "Låg", "Medel", "Hög"]},
          "priorityChoice2"       => #{contents => ["-", "Låg", "Medel", "Hög"]},
          "priorityLang"          => "Prioritet:",
          "proxyLinkMenu"         => "Skapa proxy länk",
          "recurrence"            => #{contents => ["var 15:e minut", "varje timme", "var 2:a timme", "var 4:e timme", "varje dag", "varje vecka", "var 30:e dag", "varje år"]},
          "redoMenu"              => "Återskapa\tCtrl+Y",
          "redoTool"              => #{label    => "Göra om",
                                       tooltip  => "Göra om",
                                       longhelp => "Göra om ändringar till uppgift"},
          "removeBookmarkButton"  => "Ta bort",
          "reminderCancel"        => "Avbryt",
          "reminderDlg"           => #{title => "Konfigurera påminnelse"},
          "reminderPanel"         => "Påminnelser",
          "reminderOk"            => "OK",
          "removeListButton"      => "Ta bort",
          "removeOwnerButton"     => "Ta bort",
          "replyAllMenu"          => "Svara alla\tShift+Ctrl+R",
          "replyMenu"             => "Svara avsändare\tCtrl+R",
          "restoreMenuItem"       => "Återställ databas",
          "schedulePanel"         => "Schema",
          "searchCancel"          => "Avbryt",
          "searchColumns"         => #{contents => ["Kommentar", "Skapad", "Beskrivning", "Avslutad", "Deadline", "Id", "Ägare", "Prioritet", "Delad med", "Status"]},
          "searchDlg"             => "Sök i kolumner",
          "searchOk"              => "OK",
          "searchText"            => #{tooltip  => "Skriv in söktext. Söktexter som börjar med re~ kommer att bli en regexp sökning. Söktexter som börjar med as~ kommer att bli en avancerad sökning."},
          "secTimer"              => #{tooltip  => "Sekunder"},
          "sendTaskButton"        => #{tooltip  => "Skicka meddelande om att uppgiften har blivit ändrad"},
          "setConInfoLbl"         => "Anslutning",
          "setHostLbl"            => "Datornamn:",
          "setLocalHostLbl"       => "Lokalt datornamn:",
          "setLocalPortLbl"       => "Lokal port:",
          "setPassword"           => "Lösenord:",
          "setPeerInfoLbl"        => "Peer information",
          "setPeerLbl"            => "Peer användarnamn:",
          "setPortLbl"            => "Port:",
          "setThemeLbl"           => "Tema",
          "setWebPortLbl"         => "Port:",
          "setWebUILbl"           => "Webbgränsnitt",
          "webUIEnabled"          => "Aktivera Webbgränsnitt",
          "setAvatarMenuItem"     => "Sätt avatar",
          "setRecurrence"         => "Intervall:",
          "settingsCancel"        => "Avbryt",
          "settingsDlg"           => #{title => "Nätverksinställningar"},
          "settingsOk"            => "OK",
          "setReminderButton"     => #{tooltip  => "Skapa påminnelse för uppgift"},
          "settingsMenu"          => "Nätverksinställningar",
          "shareButton"           => #{tooltip  => "Dela uppgift med användare"},
          "sharedLang"            => "Delad:",
          "sharedWithText1"       => #{tooltip  => "En lista av användarna som har uppgiften tilldelad separerade med semikolon."},
          "sharedWithText2"       => #{tooltip  => "En lista av användarna som har uppgiften tilldelad separerade med semikolon."},
          "showInReportLabel"     => "Visa uppgift i rapport",
          "showLogin"             => "Visa vid uppstart",
          "sortColumnsCancel"     => "Avbryt",
          "sortColumnsDlg"        => "Ordna kolummer",
          "sortColumnsOk"         => "OK",
          "statusChoice"          => #{contents => ["-", "Plannerad", "Pågående", "Avslutad"]},
          "statusChoice1"         => #{contents => ["-", "Plannerad", "Pågående", "Avslutad"]},
          "statusChoice2"         => #{contents => ["-", "Plannerad", "Pågående", "Avslutad"]},
          "statusLang"            => "Status:",
          "timerCancel"           => "Avbryt",
          "timerDescLbl"          => "Beskrivning:",
          "timerDlg"              => #{title => "Timer (Pomodoro)"},
          "timerOk"               => "OK",
          "timeEstimate"          => #{tooltip  => "Timmar"},
          "timeLogCheckBox"       => "Visa avslutad uppgift i \"Tidsrapport\"",
          "timeLogPanel"          => "Tidsrapport",
          "timeRemaining"         => #{tooltip  => "Timmar"},
          "timerTool"             => "Klocka",
          "todoDownTool"          => #{label    => "Lägg till på slutet",
                                       tooltip  => "Lägg till på slutet",
                                       longhelp => "Lägg till uppgift på slutet av listan"},
          "todoUpTool"            => #{label    => "Lägg till i början",
                                       tooltip  => "Lägg till i början",
                                       longhelp => "Lägg till uppgift i början av listan"},
          "undoMenu"              => "Ångra\tCtrl+Z",
          "undoTool"              => #{label    => "Ångra",
                                       tooltip  => "Ångra",
                                       longhelp => "Ångra ändringar till uppgift"},
          "updateBookmarkButton"  => "Uppdatera",
          "updateListButton"      => "Uppdatera",
          "updateOwnerButton"     => "Uppdatera",
          "useEndDate"            => "Slutdatum:",
          "useLocalButton"        => "Använd lokal uppgift",
          "useReminder"           => "Startdatum:",
          "useRemoteButton"       => "Använd cirkelns uppgift",
          "userStatusChoice"      => #{contents => ["Utloggad", "Tillgänglig", "Borta", "Upptagen"]},
          "userCancel"            => "Avbryt",
          "userDlg"               => #{title => "Dela uppgift"},
          "userOk"                => "OK",
          "useStartTime"          => "Starttid:",
          "peerStatusMsg"         => "Välj en peer för att visa status-information här...",
          "userStatusMsg"         => #{tooltip  => "Skriv in status meddelande som ska visas"},
          "webPort"               => #{tooltip  => "Portnummer att starta med, kommer att ökas om porten är upptagen."},
          "webUIEnabled"          => "Aktivera Webbgränssitt",
          "workHours"             => #{tooltip  => "Timmar"},
          "workLogCheckBox"       => "Visa uppgift utan tid i \"Tidsskrivning\"",
          "workLogLabel"          => "Rapporten visar rapporterad tid under en fem dagars period, välj startdatum:",
          "workLogPanel"          => "Tidsskrivning",
          "workMinutes"           => #{tooltip  => "Minuter"}
         }).

-define(swedishDef, #{
          all               => "Alla",
          assigned          => "Tilldelad",
          available         => "Tillgänglig",
          away              => "Borta",
          busy              => "Upptagen",
          clearMsgText      => "Rensa \"Meddelanden\" fliken",
          clearRemText      => "Rensa \"Påminnselser\" fliken",
          comment           => "Kommentar",
          compact           => "Kompakt",
          createTime        => "Skapad",
          default           => "Default",
          defInbox          => "Inbox",
          defLoggedWork     => "-- Tidsskrivning --",
          defSchedule       => "----- Schema  -----",
          defShowStatus     => "--- Visa status ---",
          defTaskList       => "Alla uppgifter",
          defTimeReport     => "--- Tidrapport  ---",
          description       => "Beskrivning",
          done              => "Avslutad",
          doneTime          => "Avslutad",
          dueTime           => "Deadline",
          estimate          => "Prognos(h)",
          high              => "Hög",
          inProgress        => "Pågående",
          listsMenu         => "Listor",
          low               => "Låg",
          medium            => "Medel",
          offline           => "Utloggad",
          orderCol          => "Kolumnordning",
          owner             => "Ägare",
          planning          => "Plannerad",
          priority          => "Prioritet",
          progress          => "Progress(%)",
          remaining         => "Kvar(h)",
          sbNotLoggedIn     => "Ej inloggad",
          sharedWith        => "Delad med",
          showCol           => "Visa kolumn",
          sortAsc           => "Sorteringsordning stigande",
          sortDec           => "Sorteringsordning nedåtgående",
          sortDef           => "Sorteringsordning standard",
          status            => "Status",
          statusMenu        => "Status",
          uid               => "Id",
          undefined         => "-",
          overdue           => "Försenade",
          today             => "Idag",
          tomorrow          => "Imorgon",
          weeksAway         => "Veckor bort",
          monthsAway        => "Månader bort",
          monday            => "Måndag",
          tuesday           => "Tisdag",
          wednesday         => "Onsdag",
          thursday          => "Torsdag",
          friday            => "Fredag",
          saturday          => "Lördag",
          sunday            => "Söndag",
          nextAlarm         => "Nästa alarm",
          timeLeft          => "Tid kvar(h)",
          timeSpent         => "Tid lagd(h)",
          timeEstimate      => "Tidsuppskattning(h)",
          taskDesc          => "Uppgiftsbeskrivning",
          total             => "Total",
          msgWebClient      => "/eWeb:index visar dina uppgifter i en webbläsare.",
          msgAltWebClient   => "/eWeb:mobile för ett alternativt webgränsnitt för telefonen."
         }).

%% The key value pairs in swedishToDB
%% Should be same as swedishDef, but value as key and key as value.
-define(swedishToDB, #{
          "-"                 => undefined,
          "Alla uppgifter"    => defTaskList,
          "Alla"              => all,
          "Avslutad"          => done,
          "Avslutad"          => doneTime,
          "Beskrivning"       => description,
          "Tillgänglig"       => available,
          "Borta"             => away,
          "Default"           => def,
          "Delad med"         => sharedWith,
          "Deadline"          => dueTime,
          "Hög"               => high,
          "Id"                => uid,
          "Kommentar"         => comment,
          "Kompakt"           => compact,
          "Låg"               => low,
          "Medel"             => medium,
          "Plannerad"         => planning,
          "Prioritet"         => priority,
          "Pågående"          => inProgress,
          "Skapad"            => createTime,
          "Status"            => status,
          "Tillgänglig"       => available,
          "Upptagen"          => busy,
          "Utloggad"          => offline,
          "var 15:e minut"    => time15,
          "var 2:a timme"     => time2h,
          "var 30:e dag"      => timeMonth,
          "var 4:e timme"     => time4h,
          "varje dag"         => timeDay,
          "varje timme"       => time1h,
          "varje vecka"       => timeWeek,
          "varje år"          => timeYear,
          "Ägare"             => owner
         }).
